CREATE TABLE `cp_banners` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
`name` VARCHAR( 60 ) NOT NULL ,
`hours` TINYINT( 2 ) UNSIGNED NOT NULL ,
`credits` INT UNSIGNED NOT NULL ,
`vote_url` VARCHAR( 255 ) NOT NULL ,
`image_url` VARCHAR( 255 ) NOT NULL ,
`created` DATETIME NOT NULL ,
`modified` DATETIME NOT NULL ,
PRIMARY KEY ( `id` )
) ENGINE = MYISAM